fixtures:
  forge_modules:
    epel:
      repo: "puppet/epel"
      ref: "3.0.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "8.4.0"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "10.9.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "8.2.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "7.2.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "8.5.0"
    yumrepo:
      repo: "puppetlabs/yumrepo_core"
      puppet_version: ">= 6.0.0"
      ref: "1.0.3"
    augeas:
      repo: "puppetlabs/augeas_core"
      puppet_version: ">= 6.0.0"
      ref: "1.0.4"
  symlinks:
    powerdns: "#{source_dir}"
